#define N_ACCESS_LEVELS 4

#define TOP_SECRET_LIT "TOP SECRET"
#define SECRET_LIT "SECRET"
#define CONFIDENTIAL_LIT "CONFIDENTIAL"
#define UNCLASSIFIED_LIT "UNCLASSIFIED"

#define TOP_SECRET_LEN 10
#define SECRET_LEN 6
#define CONFIDENTIAL_LEN 12
#define UNCLASSIFIED_LEN 12

#define TOP_SECRET 3
#define SECRET 2
#define CONFIDENTIAL 1
#define UNCLASSIFIED 0

static const char* access_level_strings[] = {
    [TOP_SECRET] = TOP_SECRET_LIT,
    [SECRET] = SECRET_LIT,
    [CONFIDENTIAL] = CONFIDENTIAL_LIT,
    [UNCLASSIFIED] = UNCLASSIFIED_LIT
};